name: Publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.8
        architecture: x64
    - name: Set env
      run: |
        echo 'OSSRH_USERNAME=${{ secrets.OSSRH_USERNAME }}' >> $GITHUB_ENV
        echo 'OSSRH_PASSWORD=${{ secrets.OSSRH_PASSWORD }}' >> $GITHUB_ENV
        echo 'SIGNING_KEYID=${{ secrets.SIGNING_KEYID }}' >> $GITHUB_ENV
        echo 'SIGNING_PASSWORD=${{ secrets.SIGNING_PASSWORD }}' >> $GITHUB_ENV
        echo 'SIGNING_KEY<<EOF' >> $GITHUB_ENV
        echo '${{ secrets.SIGNING_KEY }}' >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Gradle clean
      run: |
        ./gradlew clean
    - name: Gradle build
      run: |
        ./gradlew build
    - name: Gradle publish to mavenLocal
      run: |
        PUBLISH_PRODUCTION=1 ./gradlew publishToMavenLocal
    - name: Gradle publish to maven central
      run: |
        PUBLISH_PRODUCTION=1 ./gradlew publish
